apiVersion: v1
kind: ConfigMap
metadata:
  name: psihoterapija-ikar-config
  namespace: prod
  labels:
    app: psihoterapija-ikar
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "3000"
  PUBLIC_SITE_URL: "https://psihoterapija-ikar.rs"
  UPLOADS_DIR: "/app/data/uploads"
