apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psihoterapija-ikar-data
  namespace: prod
  labels:
    app: psihoterapija-ikar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
